//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GoHorse.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGoHorseListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class GoHorseBaseListener : IGoHorseListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] GoHorseParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] GoHorseParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStat([NotNull] GoHorseParser.StatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStat([NotNull] GoHorseParser.StatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.readln"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReadln([NotNull] GoHorseParser.ReadlnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.readln"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReadln([NotNull] GoHorseParser.ReadlnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.writeln"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWriteln([NotNull] GoHorseParser.WritelnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.writeln"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWriteln([NotNull] GoHorseParser.WritelnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.ifStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStat([NotNull] GoHorseParser.IfStatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.ifStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStat([NotNull] GoHorseParser.IfStatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.whileStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStat([NotNull] GoHorseParser.WhileStatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.whileStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStat([NotNull] GoHorseParser.WhileStatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.untilStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUntilStat([NotNull] GoHorseParser.UntilStatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.untilStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUntilStat([NotNull] GoHorseParser.UntilStatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.forStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStat([NotNull] GoHorseParser.ForStatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.forStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStat([NotNull] GoHorseParser.ForStatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssign([NotNull] GoHorseParser.AssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssign([NotNull] GoHorseParser.AssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDecl([NotNull] GoHorseParser.VarDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDecl([NotNull] GoHorseParser.VarDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] GoHorseParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] GoHorseParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.refeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRefeExpr([NotNull] GoHorseParser.RefeExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.refeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRefeExpr([NotNull] GoHorseParser.RefeExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc([NotNull] GoHorseParser.FuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc([NotNull] GoHorseParser.FuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParams([NotNull] GoHorseParser.ParamsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParams([NotNull] GoHorseParser.ParamsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam([NotNull] GoHorseParser.ParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam([NotNull] GoHorseParser.ParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.orExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrExpr([NotNull] GoHorseParser.OrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.orExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrExpr([NotNull] GoHorseParser.OrExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpr([NotNull] GoHorseParser.AndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpr([NotNull] GoHorseParser.AndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.equalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualExpr([NotNull] GoHorseParser.EqualExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.equalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualExpr([NotNull] GoHorseParser.EqualExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.relatExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelatExpr([NotNull] GoHorseParser.RelatExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.relatExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelatExpr([NotNull] GoHorseParser.RelatExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.addExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddExpr([NotNull] GoHorseParser.AddExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.addExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddExpr([NotNull] GoHorseParser.AddExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.multExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultExpr([NotNull] GoHorseParser.MultExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.multExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultExpr([NotNull] GoHorseParser.MultExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.unary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_expr([NotNull] GoHorseParser.Unary_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.unary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_expr([NotNull] GoHorseParser.Unary_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.primary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary_expr([NotNull] GoHorseParser.Primary_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.primary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary_expr([NotNull] GoHorseParser.Primary_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] GoHorseParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] GoHorseParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] GoHorseParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] GoHorseParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] GoHorseParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] GoHorseParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] GoHorseParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] GoHorseParser.TypeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
