//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GoHorse.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GoHorseParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface IGoHorseListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] GoHorseParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] GoHorseParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat([NotNull] GoHorseParser.StatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat([NotNull] GoHorseParser.StatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.readln"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReadln([NotNull] GoHorseParser.ReadlnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.readln"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReadln([NotNull] GoHorseParser.ReadlnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.writeln"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWriteln([NotNull] GoHorseParser.WritelnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.writeln"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWriteln([NotNull] GoHorseParser.WritelnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStat([NotNull] GoHorseParser.IfStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStat([NotNull] GoHorseParser.IfStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.whileStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStat([NotNull] GoHorseParser.WhileStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.whileStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStat([NotNull] GoHorseParser.WhileStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.untilStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUntilStat([NotNull] GoHorseParser.UntilStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.untilStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUntilStat([NotNull] GoHorseParser.UntilStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.forStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStat([NotNull] GoHorseParser.ForStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.forStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStat([NotNull] GoHorseParser.ForStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssign([NotNull] GoHorseParser.AssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssign([NotNull] GoHorseParser.AssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDecl([NotNull] GoHorseParser.VarDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDecl([NotNull] GoHorseParser.VarDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] GoHorseParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] GoHorseParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.refeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRefeExpr([NotNull] GoHorseParser.RefeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.refeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRefeExpr([NotNull] GoHorseParser.RefeExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc([NotNull] GoHorseParser.FuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc([NotNull] GoHorseParser.FuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParams([NotNull] GoHorseParser.ParamsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParams([NotNull] GoHorseParser.ParamsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] GoHorseParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] GoHorseParser.ParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpr([NotNull] GoHorseParser.OrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpr([NotNull] GoHorseParser.OrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] GoHorseParser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] GoHorseParser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.equalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualExpr([NotNull] GoHorseParser.EqualExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.equalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualExpr([NotNull] GoHorseParser.EqualExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.relatExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelatExpr([NotNull] GoHorseParser.RelatExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.relatExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelatExpr([NotNull] GoHorseParser.RelatExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.addExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddExpr([NotNull] GoHorseParser.AddExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.addExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddExpr([NotNull] GoHorseParser.AddExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.multExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultExpr([NotNull] GoHorseParser.MultExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.multExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultExpr([NotNull] GoHorseParser.MultExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.unary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_expr([NotNull] GoHorseParser.Unary_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.unary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_expr([NotNull] GoHorseParser.Unary_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.primary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary_expr([NotNull] GoHorseParser.Primary_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.primary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary_expr([NotNull] GoHorseParser.Primary_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] GoHorseParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] GoHorseParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] GoHorseParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] GoHorseParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] GoHorseParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] GoHorseParser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoHorseParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] GoHorseParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoHorseParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] GoHorseParser.TypeContext context);
}
